### PR TITLE
Updated last example in README.md to improve readability/understanding

### PR DESCRIPTION
**Pull request by steveafrost**
This pull request has been automatically created by learn.co.

### CODE REVIEW

**Comment by gj** [comment]
Hey @steveafrost, what's the purpose of this change?

**Comment by steveafrost** [comment]
Hey @gj, the change moves the variable declarations (or even a missing declaration in the first instance of just `user` though I think that is on purpose) to be in the same order as the console logs happening below.

So instead of

ab then ba
The readme instead reads
ab then ab

Does that help/make sense?

**Comment by gj** [comment]
Thanks @steveafrost !

Made some more changes to bring everything in line. Let me know if anything looks awry!

**Comment by steveafrost** [comment]
Looks great, thanks! :)

**Pull request merged**
